name:                pswasm
version:             0.1.0.0
github:              "githubuser/pswasm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"
data-files:          "static/naive/runtime.wat"

extra-source-files:
- README.md
- CHANGELOG.md 

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ps-wasm#readme>

dependencies:
- base
- text
- bytestring
- aeson
- purescript
- filepath
- filemanip
- directory
- process
- hspec
- hspec-discover
- hspec-contrib
- HUnit
- QuickCheck
- criterion
#- transformers
#- containers
#- time
#- language-javascript
#- sourcemap
#- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pswasm-64bit:
    main:                Main64Bit.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Main64Bit
    dependencies:
    - pswasm
    other-modules: Paths_pswasm

  pswasm-32bit:
    main:                Main32Bit.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Main32Bit
    dependencies:
    - pswasm
    other-modules: Paths_pswasm

  pswasm-3132bit:
    main:                Main3132Bit.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Main3132Bit
    dependencies:
    - pswasm
    other-modules: Paths_pswasm

tests:
  pswasm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pswasm
